services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: escape_game
      MYSQL_USER: escape_user
      MYSQL_PASSWORD: escape_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init_db_script:/docker-entrypoint-initdb.d/
    
  phpmyadmin:
    image: phpmyadmin:5.2.2
    ports:
      - 8095:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306 
      UPLOAD_LIMIT: '512M'
    depends_on:
      - mariadb

  backend:
    build: ./Backend
    command: >
      /bin/sh -c "npm i; npm run dev"
    environment:
      DB_HOST: mariadb
      DB_USER: escape_user
      DB_PASSWORD: escape_pass
      DB_NAME: escape_game
    depends_on:
      - mariadb
    ports:
      - "3001:3000"

  frontend:
    build: ./frontend
    command: >
      /bin/sh -c "npm i; npm run dev"
    ports:
      - "3000:3000"

volumes:
  mariadb_data: