{
 "title": "Node.js API Prometheus Metrics",
 "tags": [
  "nodejs",
  "prometheus",
  "api"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Requêtes HTTP (par route)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (route)",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Latence moyenne (s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "latence moyenne"
    }
   ]
  },
  {
   "title": "P95 Latence (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Erreurs HTTP (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[1m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}